// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outline

import (
	"context"

	"github.com/nepriyatelev/outline-client-go/internal/contracts"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoer {
	mock := &MockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer struct {
	mock.Mock
}

type MockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoer) EXPECT() *MockDoer_Expecter {
	return &MockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockDoer
func (_mock *MockDoer) Do(ctx context.Context, req *contracts.Request) (*contracts.Response, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *contracts.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *contracts.Request) (*contracts.Response, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *contracts.Request) *contracts.Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *contracts.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - req *contracts.Request
func (_e *MockDoer_Expecter) Do(ctx interface{}, req interface{}) *MockDoer_Do_Call {
	return &MockDoer_Do_Call{Call: _e.mock.On("Do", ctx, req)}
}

func (_c *MockDoer_Do_Call) Run(run func(ctx context.Context, req *contracts.Request)) *MockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *contracts.Request
		if args[1] != nil {
			arg1 = args[1].(*contracts.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDoer_Do_Call) Return(response *contracts.Response, err error) *MockDoer_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockDoer_Do_Call) RunAndReturn(run func(ctx context.Context, req *contracts.Request) (*contracts.Response, error)) *MockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debugf provides a mock function for the type MockLogger
func (_mock *MockLogger) Debugf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Debugf(ctx interface{}, format interface{}, args ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type MockLogger
func (_mock *MockLogger) Infof(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Infof(ctx interface{}, format interface{}, args ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}
