// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outline

import (
	"context"
	"time"

	"github.com/nepriyatelev/outline-client-go/internal/contracts"
	"github.com/nepriyatelev/outline-client-go/outline/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientOutline creates a new instance of MockClientOutline. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientOutline(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientOutline {
	mock := &MockClientOutline{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientOutline is an autogenerated mock type for the ClientOutline type
type MockClientOutline struct {
	mock.Mock
}

type MockClientOutline_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientOutline) EXPECT() *MockClientOutline_Expecter {
	return &MockClientOutline_Expecter{mock: &_m.Mock}
}

// CreateAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) CreateAccessKey(ctx context.Context, createAccessKey *types.CreateAccessKey) (*types.AccessKey, error) {
	ret := _mock.Called(ctx, createAccessKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessKey")
	}

	var r0 *types.AccessKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.CreateAccessKey) (*types.AccessKey, error)); ok {
		return returnFunc(ctx, createAccessKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.CreateAccessKey) *types.AccessKey); ok {
		r0 = returnFunc(ctx, createAccessKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AccessKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.CreateAccessKey) error); ok {
		r1 = returnFunc(ctx, createAccessKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_CreateAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessKey'
type MockClientOutline_CreateAccessKey_Call struct {
	*mock.Call
}

// CreateAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - createAccessKey *types.CreateAccessKey
func (_e *MockClientOutline_Expecter) CreateAccessKey(ctx interface{}, createAccessKey interface{}) *MockClientOutline_CreateAccessKey_Call {
	return &MockClientOutline_CreateAccessKey_Call{Call: _e.mock.On("CreateAccessKey", ctx, createAccessKey)}
}

func (_c *MockClientOutline_CreateAccessKey_Call) Run(run func(ctx context.Context, createAccessKey *types.CreateAccessKey)) *MockClientOutline_CreateAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.CreateAccessKey
		if args[1] != nil {
			arg1 = args[1].(*types.CreateAccessKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_CreateAccessKey_Call) Return(accessKey *types.AccessKey, err error) *MockClientOutline_CreateAccessKey_Call {
	_c.Call.Return(accessKey, err)
	return _c
}

func (_c *MockClientOutline_CreateAccessKey_Call) RunAndReturn(run func(ctx context.Context, createAccessKey *types.CreateAccessKey) (*types.AccessKey, error)) *MockClientOutline_CreateAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) DeleteAccessKey(ctx context.Context, accessKeyID string) error {
	ret := _mock.Called(ctx, accessKeyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_DeleteAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessKey'
type MockClientOutline_DeleteAccessKey_Call struct {
	*mock.Call
}

// DeleteAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
func (_e *MockClientOutline_Expecter) DeleteAccessKey(ctx interface{}, accessKeyID interface{}) *MockClientOutline_DeleteAccessKey_Call {
	return &MockClientOutline_DeleteAccessKey_Call{Call: _e.mock.On("DeleteAccessKey", ctx, accessKeyID)}
}

func (_c *MockClientOutline_DeleteAccessKey_Call) Run(run func(ctx context.Context, accessKeyID string)) *MockClientOutline_DeleteAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_DeleteAccessKey_Call) Return(err error) *MockClientOutline_DeleteAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_DeleteAccessKey_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string) error) *MockClientOutline_DeleteAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDataLimitAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) DeleteDataLimitAccessKey(ctx context.Context, accessKeyID string) error {
	ret := _mock.Called(ctx, accessKeyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDataLimitAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_DeleteDataLimitAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDataLimitAccessKey'
type MockClientOutline_DeleteDataLimitAccessKey_Call struct {
	*mock.Call
}

// DeleteDataLimitAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
func (_e *MockClientOutline_Expecter) DeleteDataLimitAccessKey(ctx interface{}, accessKeyID interface{}) *MockClientOutline_DeleteDataLimitAccessKey_Call {
	return &MockClientOutline_DeleteDataLimitAccessKey_Call{Call: _e.mock.On("DeleteDataLimitAccessKey", ctx, accessKeyID)}
}

func (_c *MockClientOutline_DeleteDataLimitAccessKey_Call) Run(run func(ctx context.Context, accessKeyID string)) *MockClientOutline_DeleteDataLimitAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_DeleteDataLimitAccessKey_Call) Return(err error) *MockClientOutline_DeleteDataLimitAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_DeleteDataLimitAccessKey_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string) error) *MockClientOutline_DeleteDataLimitAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyLimitBytes provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) DeleteKeyLimitBytes(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyLimitBytes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_DeleteKeyLimitBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyLimitBytes'
type MockClientOutline_DeleteKeyLimitBytes_Call struct {
	*mock.Call
}

// DeleteKeyLimitBytes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientOutline_Expecter) DeleteKeyLimitBytes(ctx interface{}) *MockClientOutline_DeleteKeyLimitBytes_Call {
	return &MockClientOutline_DeleteKeyLimitBytes_Call{Call: _e.mock.On("DeleteKeyLimitBytes", ctx)}
}

func (_c *MockClientOutline_DeleteKeyLimitBytes_Call) Run(run func(ctx context.Context)) *MockClientOutline_DeleteKeyLimitBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientOutline_DeleteKeyLimitBytes_Call) Return(err error) *MockClientOutline_DeleteKeyLimitBytes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_DeleteKeyLimitBytes_Call) RunAndReturn(run func(ctx context.Context) error) *MockClientOutline_DeleteKeyLimitBytes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) GetAccessKey(ctx context.Context, accessKeyID string) (*types.AccessKey, error) {
	ret := _mock.Called(ctx, accessKeyID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessKey")
	}

	var r0 *types.AccessKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.AccessKey, error)); ok {
		return returnFunc(ctx, accessKeyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.AccessKey); ok {
		r0 = returnFunc(ctx, accessKeyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AccessKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessKeyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_GetAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessKey'
type MockClientOutline_GetAccessKey_Call struct {
	*mock.Call
}

// GetAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
func (_e *MockClientOutline_Expecter) GetAccessKey(ctx interface{}, accessKeyID interface{}) *MockClientOutline_GetAccessKey_Call {
	return &MockClientOutline_GetAccessKey_Call{Call: _e.mock.On("GetAccessKey", ctx, accessKeyID)}
}

func (_c *MockClientOutline_GetAccessKey_Call) Run(run func(ctx context.Context, accessKeyID string)) *MockClientOutline_GetAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_GetAccessKey_Call) Return(accessKey *types.AccessKey, err error) *MockClientOutline_GetAccessKey_Call {
	_c.Call.Return(accessKey, err)
	return _c
}

func (_c *MockClientOutline_GetAccessKey_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string) (*types.AccessKey, error)) *MockClientOutline_GetAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessKeys provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) GetAccessKeys(ctx context.Context) ([]*types.AccessKey, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessKeys")
	}

	var r0 []*types.AccessKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*types.AccessKey, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*types.AccessKey); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.AccessKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_GetAccessKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessKeys'
type MockClientOutline_GetAccessKeys_Call struct {
	*mock.Call
}

// GetAccessKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientOutline_Expecter) GetAccessKeys(ctx interface{}) *MockClientOutline_GetAccessKeys_Call {
	return &MockClientOutline_GetAccessKeys_Call{Call: _e.mock.On("GetAccessKeys", ctx)}
}

func (_c *MockClientOutline_GetAccessKeys_Call) Run(run func(ctx context.Context)) *MockClientOutline_GetAccessKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientOutline_GetAccessKeys_Call) Return(accessKeys []*types.AccessKey, err error) *MockClientOutline_GetAccessKeys_Call {
	_c.Call.Return(accessKeys, err)
	return _c
}

func (_c *MockClientOutline_GetAccessKeys_Call) RunAndReturn(run func(ctx context.Context) ([]*types.AccessKey, error)) *MockClientOutline_GetAccessKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperimentalMetrics provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) GetExperimentalMetrics(ctx context.Context, since time.Duration) (*types.ExperimentalMetricsResponse, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for GetExperimentalMetrics")
	}

	var r0 *types.ExperimentalMetricsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (*types.ExperimentalMetricsResponse, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) *types.ExperimentalMetricsResponse); ok {
		r0 = returnFunc(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ExperimentalMetricsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_GetExperimentalMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentalMetrics'
type MockClientOutline_GetExperimentalMetrics_Call struct {
	*mock.Call
}

// GetExperimentalMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Duration
func (_e *MockClientOutline_Expecter) GetExperimentalMetrics(ctx interface{}, since interface{}) *MockClientOutline_GetExperimentalMetrics_Call {
	return &MockClientOutline_GetExperimentalMetrics_Call{Call: _e.mock.On("GetExperimentalMetrics", ctx, since)}
}

func (_c *MockClientOutline_GetExperimentalMetrics_Call) Run(run func(ctx context.Context, since time.Duration)) *MockClientOutline_GetExperimentalMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_GetExperimentalMetrics_Call) Return(experimentalMetricsResponse *types.ExperimentalMetricsResponse, err error) *MockClientOutline_GetExperimentalMetrics_Call {
	_c.Call.Return(experimentalMetricsResponse, err)
	return _c
}

func (_c *MockClientOutline_GetExperimentalMetrics_Call) RunAndReturn(run func(ctx context.Context, since time.Duration) (*types.ExperimentalMetricsResponse, error)) *MockClientOutline_GetExperimentalMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetricsEnabled provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) GetMetricsEnabled(ctx context.Context) (*types.MetricsEnabled, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricsEnabled")
	}

	var r0 *types.MetricsEnabled
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*types.MetricsEnabled, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *types.MetricsEnabled); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MetricsEnabled)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_GetMetricsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetricsEnabled'
type MockClientOutline_GetMetricsEnabled_Call struct {
	*mock.Call
}

// GetMetricsEnabled is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientOutline_Expecter) GetMetricsEnabled(ctx interface{}) *MockClientOutline_GetMetricsEnabled_Call {
	return &MockClientOutline_GetMetricsEnabled_Call{Call: _e.mock.On("GetMetricsEnabled", ctx)}
}

func (_c *MockClientOutline_GetMetricsEnabled_Call) Run(run func(ctx context.Context)) *MockClientOutline_GetMetricsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientOutline_GetMetricsEnabled_Call) Return(metricsEnabled *types.MetricsEnabled, err error) *MockClientOutline_GetMetricsEnabled_Call {
	_c.Call.Return(metricsEnabled, err)
	return _c
}

func (_c *MockClientOutline_GetMetricsEnabled_Call) RunAndReturn(run func(ctx context.Context) (*types.MetricsEnabled, error)) *MockClientOutline_GetMetricsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetricsTransfer provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) GetMetricsTransfer(ctx context.Context) (*types.MetricsTransfer, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricsTransfer")
	}

	var r0 *types.MetricsTransfer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*types.MetricsTransfer, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *types.MetricsTransfer); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MetricsTransfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_GetMetricsTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetricsTransfer'
type MockClientOutline_GetMetricsTransfer_Call struct {
	*mock.Call
}

// GetMetricsTransfer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientOutline_Expecter) GetMetricsTransfer(ctx interface{}) *MockClientOutline_GetMetricsTransfer_Call {
	return &MockClientOutline_GetMetricsTransfer_Call{Call: _e.mock.On("GetMetricsTransfer", ctx)}
}

func (_c *MockClientOutline_GetMetricsTransfer_Call) Run(run func(ctx context.Context)) *MockClientOutline_GetMetricsTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientOutline_GetMetricsTransfer_Call) Return(metricsTransfer *types.MetricsTransfer, err error) *MockClientOutline_GetMetricsTransfer_Call {
	_c.Call.Return(metricsTransfer, err)
	return _c
}

func (_c *MockClientOutline_GetMetricsTransfer_Call) RunAndReturn(run func(ctx context.Context) (*types.MetricsTransfer, error)) *MockClientOutline_GetMetricsTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerInfo provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) GetServerInfo(ctx context.Context) (*types.ServerInfoResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetServerInfo")
	}

	var r0 *types.ServerInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*types.ServerInfoResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *types.ServerInfoResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServerInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_GetServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerInfo'
type MockClientOutline_GetServerInfo_Call struct {
	*mock.Call
}

// GetServerInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientOutline_Expecter) GetServerInfo(ctx interface{}) *MockClientOutline_GetServerInfo_Call {
	return &MockClientOutline_GetServerInfo_Call{Call: _e.mock.On("GetServerInfo", ctx)}
}

func (_c *MockClientOutline_GetServerInfo_Call) Run(run func(ctx context.Context)) *MockClientOutline_GetServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientOutline_GetServerInfo_Call) Return(serverInfoResponse *types.ServerInfoResponse, err error) *MockClientOutline_GetServerInfo_Call {
	_c.Call.Return(serverInfoResponse, err)
	return _c
}

func (_c *MockClientOutline_GetServerInfo_Call) RunAndReturn(run func(ctx context.Context) (*types.ServerInfoResponse, error)) *MockClientOutline_GetServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateAccessKey(ctx context.Context, accessKeyID string, updateAccessKey *types.AccessKey) (*types.AccessKey, error) {
	ret := _mock.Called(ctx, accessKeyID, updateAccessKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccessKey")
	}

	var r0 *types.AccessKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *types.AccessKey) (*types.AccessKey, error)); ok {
		return returnFunc(ctx, accessKeyID, updateAccessKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *types.AccessKey) *types.AccessKey); ok {
		r0 = returnFunc(ctx, accessKeyID, updateAccessKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AccessKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *types.AccessKey) error); ok {
		r1 = returnFunc(ctx, accessKeyID, updateAccessKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientOutline_UpdateAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccessKey'
type MockClientOutline_UpdateAccessKey_Call struct {
	*mock.Call
}

// UpdateAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - updateAccessKey *types.AccessKey
func (_e *MockClientOutline_Expecter) UpdateAccessKey(ctx interface{}, accessKeyID interface{}, updateAccessKey interface{}) *MockClientOutline_UpdateAccessKey_Call {
	return &MockClientOutline_UpdateAccessKey_Call{Call: _e.mock.On("UpdateAccessKey", ctx, accessKeyID, updateAccessKey)}
}

func (_c *MockClientOutline_UpdateAccessKey_Call) Run(run func(ctx context.Context, accessKeyID string, updateAccessKey *types.AccessKey)) *MockClientOutline_UpdateAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *types.AccessKey
		if args[2] != nil {
			arg2 = args[2].(*types.AccessKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateAccessKey_Call) Return(accessKey *types.AccessKey, err error) *MockClientOutline_UpdateAccessKey_Call {
	_c.Call.Return(accessKey, err)
	return _c
}

func (_c *MockClientOutline_UpdateAccessKey_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, updateAccessKey *types.AccessKey) (*types.AccessKey, error)) *MockClientOutline_UpdateAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataLimitAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateDataLimitAccessKey(ctx context.Context, accessKeyID string, bytes uint64) error {
	ret := _mock.Called(ctx, accessKeyID, bytes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataLimitAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = returnFunc(ctx, accessKeyID, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdateDataLimitAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataLimitAccessKey'
type MockClientOutline_UpdateDataLimitAccessKey_Call struct {
	*mock.Call
}

// UpdateDataLimitAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - bytes uint64
func (_e *MockClientOutline_Expecter) UpdateDataLimitAccessKey(ctx interface{}, accessKeyID interface{}, bytes interface{}) *MockClientOutline_UpdateDataLimitAccessKey_Call {
	return &MockClientOutline_UpdateDataLimitAccessKey_Call{Call: _e.mock.On("UpdateDataLimitAccessKey", ctx, accessKeyID, bytes)}
}

func (_c *MockClientOutline_UpdateDataLimitAccessKey_Call) Run(run func(ctx context.Context, accessKeyID string, bytes uint64)) *MockClientOutline_UpdateDataLimitAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateDataLimitAccessKey_Call) Return(err error) *MockClientOutline_UpdateDataLimitAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdateDataLimitAccessKey_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, bytes uint64) error) *MockClientOutline_UpdateDataLimitAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateKeyLimitBytes provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateKeyLimitBytes(ctx context.Context, bytes uint64) error {
	ret := _mock.Called(ctx, bytes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKeyLimitBytes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdateKeyLimitBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateKeyLimitBytes'
type MockClientOutline_UpdateKeyLimitBytes_Call struct {
	*mock.Call
}

// UpdateKeyLimitBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - bytes uint64
func (_e *MockClientOutline_Expecter) UpdateKeyLimitBytes(ctx interface{}, bytes interface{}) *MockClientOutline_UpdateKeyLimitBytes_Call {
	return &MockClientOutline_UpdateKeyLimitBytes_Call{Call: _e.mock.On("UpdateKeyLimitBytes", ctx, bytes)}
}

func (_c *MockClientOutline_UpdateKeyLimitBytes_Call) Run(run func(ctx context.Context, bytes uint64)) *MockClientOutline_UpdateKeyLimitBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateKeyLimitBytes_Call) Return(err error) *MockClientOutline_UpdateKeyLimitBytes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdateKeyLimitBytes_Call) RunAndReturn(run func(ctx context.Context, bytes uint64) error) *MockClientOutline_UpdateKeyLimitBytes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetricsEnabled provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateMetricsEnabled(ctx context.Context, enabled bool) error {
	ret := _mock.Called(ctx, enabled)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetricsEnabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = returnFunc(ctx, enabled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdateMetricsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetricsEnabled'
type MockClientOutline_UpdateMetricsEnabled_Call struct {
	*mock.Call
}

// UpdateMetricsEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - enabled bool
func (_e *MockClientOutline_Expecter) UpdateMetricsEnabled(ctx interface{}, enabled interface{}) *MockClientOutline_UpdateMetricsEnabled_Call {
	return &MockClientOutline_UpdateMetricsEnabled_Call{Call: _e.mock.On("UpdateMetricsEnabled", ctx, enabled)}
}

func (_c *MockClientOutline_UpdateMetricsEnabled_Call) Run(run func(ctx context.Context, enabled bool)) *MockClientOutline_UpdateMetricsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateMetricsEnabled_Call) Return(err error) *MockClientOutline_UpdateMetricsEnabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdateMetricsEnabled_Call) RunAndReturn(run func(ctx context.Context, enabled bool) error) *MockClientOutline_UpdateMetricsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNameAccessKey provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateNameAccessKey(ctx context.Context, accessKeyID string, newName string) error {
	ret := _mock.Called(ctx, accessKeyID, newName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNameAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdateNameAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNameAccessKey'
type MockClientOutline_UpdateNameAccessKey_Call struct {
	*mock.Call
}

// UpdateNameAccessKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - newName string
func (_e *MockClientOutline_Expecter) UpdateNameAccessKey(ctx interface{}, accessKeyID interface{}, newName interface{}) *MockClientOutline_UpdateNameAccessKey_Call {
	return &MockClientOutline_UpdateNameAccessKey_Call{Call: _e.mock.On("UpdateNameAccessKey", ctx, accessKeyID, newName)}
}

func (_c *MockClientOutline_UpdateNameAccessKey_Call) Run(run func(ctx context.Context, accessKeyID string, newName string)) *MockClientOutline_UpdateNameAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateNameAccessKey_Call) Return(err error) *MockClientOutline_UpdateNameAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdateNameAccessKey_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, newName string) error) *MockClientOutline_UpdateNameAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePortNewAccessKeys provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdatePortNewAccessKeys(ctx context.Context, port uint16) error {
	ret := _mock.Called(ctx, port)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePortNewAccessKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16) error); ok {
		r0 = returnFunc(ctx, port)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdatePortNewAccessKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePortNewAccessKeys'
type MockClientOutline_UpdatePortNewAccessKeys_Call struct {
	*mock.Call
}

// UpdatePortNewAccessKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - port uint16
func (_e *MockClientOutline_Expecter) UpdatePortNewAccessKeys(ctx interface{}, port interface{}) *MockClientOutline_UpdatePortNewAccessKeys_Call {
	return &MockClientOutline_UpdatePortNewAccessKeys_Call{Call: _e.mock.On("UpdatePortNewAccessKeys", ctx, port)}
}

func (_c *MockClientOutline_UpdatePortNewAccessKeys_Call) Run(run func(ctx context.Context, port uint16)) *MockClientOutline_UpdatePortNewAccessKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdatePortNewAccessKeys_Call) Return(err error) *MockClientOutline_UpdatePortNewAccessKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdatePortNewAccessKeys_Call) RunAndReturn(run func(ctx context.Context, port uint16) error) *MockClientOutline_UpdatePortNewAccessKeys_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateServerHostname provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateServerHostname(ctx context.Context, hostnameOrIP string) error {
	ret := _mock.Called(ctx, hostnameOrIP)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServerHostname")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hostnameOrIP)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdateServerHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateServerHostname'
type MockClientOutline_UpdateServerHostname_Call struct {
	*mock.Call
}

// UpdateServerHostname is a helper method to define mock.On call
//   - ctx context.Context
//   - hostnameOrIP string
func (_e *MockClientOutline_Expecter) UpdateServerHostname(ctx interface{}, hostnameOrIP interface{}) *MockClientOutline_UpdateServerHostname_Call {
	return &MockClientOutline_UpdateServerHostname_Call{Call: _e.mock.On("UpdateServerHostname", ctx, hostnameOrIP)}
}

func (_c *MockClientOutline_UpdateServerHostname_Call) Run(run func(ctx context.Context, hostnameOrIP string)) *MockClientOutline_UpdateServerHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateServerHostname_Call) Return(err error) *MockClientOutline_UpdateServerHostname_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdateServerHostname_Call) RunAndReturn(run func(ctx context.Context, hostnameOrIP string) error) *MockClientOutline_UpdateServerHostname_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateServerName provides a mock function for the type MockClientOutline
func (_mock *MockClientOutline) UpdateServerName(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServerName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientOutline_UpdateServerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateServerName'
type MockClientOutline_UpdateServerName_Call struct {
	*mock.Call
}

// UpdateServerName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClientOutline_Expecter) UpdateServerName(ctx interface{}, name interface{}) *MockClientOutline_UpdateServerName_Call {
	return &MockClientOutline_UpdateServerName_Call{Call: _e.mock.On("UpdateServerName", ctx, name)}
}

func (_c *MockClientOutline_UpdateServerName_Call) Run(run func(ctx context.Context, name string)) *MockClientOutline_UpdateServerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientOutline_UpdateServerName_Call) Return(err error) *MockClientOutline_UpdateServerName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientOutline_UpdateServerName_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockClientOutline_UpdateServerName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoer {
	mock := &MockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer struct {
	mock.Mock
}

type MockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoer) EXPECT() *MockDoer_Expecter {
	return &MockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockDoer
func (_mock *MockDoer) Do(ctx context.Context, req *contracts.Request) (*contracts.Response, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *contracts.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *contracts.Request) (*contracts.Response, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *contracts.Request) *contracts.Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *contracts.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - req *contracts.Request
func (_e *MockDoer_Expecter) Do(ctx interface{}, req interface{}) *MockDoer_Do_Call {
	return &MockDoer_Do_Call{Call: _e.mock.On("Do", ctx, req)}
}

func (_c *MockDoer_Do_Call) Run(run func(ctx context.Context, req *contracts.Request)) *MockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *contracts.Request
		if args[1] != nil {
			arg1 = args[1].(*contracts.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDoer_Do_Call) Return(response *contracts.Response, err error) *MockDoer_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockDoer_Do_Call) RunAndReturn(run func(ctx context.Context, req *contracts.Request) (*contracts.Response, error)) *MockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debugf provides a mock function for the type MockLogger
func (_mock *MockLogger) Debugf(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Debugf(ctx interface{}, format interface{}, args ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type MockLogger
func (_mock *MockLogger) Infof(ctx context.Context, format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, format, args)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Infof(ctx interface{}, format interface{}, args ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{ctx, format}, args...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(ctx context.Context, format string, args ...any)) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(ctx context.Context, format string, args ...any)) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}
